# Site settings
author: Firooz Mafakheri
title: Firooz's first blog 
header-img: img/home-bg.png
email: firooz.mafakheri@gmail.com
copyright_name: Firooz Mafakheri
description: > # this means to ignore newlines until "baseurl:"
  about me 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Firooz-Bright

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
